# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

ruby '3.0.1'

gem 'roda', '~> 3.49'
gem 'puma', '~> 5.5'
gem 'rack-cors', '~> 1.1'
gem 'rake', '~> 13.0'

gem 'i18n', '~> 1.8'
gem 'config', '~> 3.1'

gem 'dry-initializer', '~> 3.0'
gem 'dry-validation', '~> 1.7'

gem 'activesupport', '~> 6.0', require: false

gem 'waterdrop', '~> 1.4'
gem 'karafka', '~> 1.4'
gem "schema_registry", path: "../schema_registry"

gem 'pg', '~> 1.2'
gem 'sequel', '~> 5.50'
gem 'jwt', '~> 2.3'

gem "sidekiq", '~> 6.3'

gem 'jsonapi-serializer', '~> 2.2'

group :development, :test do
  gem 'ruby_jard', '~> 0.3'
  gem 'rubocop-airbnb', '~> 4.0'

  gem 'rspec', '~> 3.10'
  gem 'fabrication', '~> 2.22'
  gem 'rack-test', '~> 1.1'
  gem 'database_cleaner-sequel', '~> 2.0'
end
