app:
  secret: <%= ENV.fetch('APP_SECRET') %>
db:
  port: <%= ENV.fetch('DB_PORT') %>
  host: <%= ENV.fetch('DB_HOST') %>
  user: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  database: async_accounting_production
redis:
  port: <%= ENV.fetch('REDIS_PORT') %>
  db: <%= ENV.fetch('REDIS_DB') %>
  sidekiq_db: <%= ENV.fetch('REDIS_SIDEKIQ_DB') %>
