app:
  name: 'async-accounting'
  secret: not-secure
db:
  adapter: postgresql
  host: localhost
  port: 5432
kafka:
  topics:
    authentication: 'auth-stream'
    tasks: 'tasks-stream'
    accounting: 'accounting-stream'
    billing: 'billing-lifecycle'
